version: "3.1"
services:
  db:                                                                                                                                                     
    image: postgres:alpine                                                                                                                                
    volumes:                                                                                                                                              
      - postgres_db:/var/lib/postgresql/data                                                                                                              
      - ./dbfiles:/dbfiles 
      - ./dbfiles/init.sql:/docker-entrypoint-initdb.d/init.sql                                                                                                                               
    env_file:                                                                                                                                             
      - env
  app:
    image: homes      
    environment:
      - PYTHONUNBUFFERED=1    
    container_name: homes_container
    env_file:
      - env
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    volumes:
      - ./:/app
volumes:                                                                                                                                                  
  postgres_db: